#ifndef _I2C_ERRORS_H
#define _I2C_ERRORS_H

#include <3ds/result.h>

// module specific os

#define OS_REMOTE_SESSION_CLOSED         MAKERESULT(RL_STATUS   , RS_CANCELED, RM_OS, 26) // C920181A
#define OS_INVALID_IPC_ARGUMENT          MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 48) // D9001830
#define OS_INVALID_IPC_HEADER            MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 47) // D900182F
#define OS_EXCEEDED_HANDLES_INDEX        MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 49) // D9001831

// general os

#define OS_MISALIGNED_ADDRESS            MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_OS, RD_MISALIGNED_ADDRESS)

// general i2c

#define I2C_INTERNAL_RANGE               MAKERESULT(RL_FATAL, RS_INTERNAL    , RM_I2C, RD_OUT_OF_RANGE)
#define I2C_INVALID_SIZE                 MAKERESULT(RL_USAGE, RS_INVALIDARG  , RM_I2C, RD_INVALID_SIZE)
#define I2C_UNAUTHORIZED                 MAKERESULT(RL_USAGE, RS_INVALIDSTATE, RM_I2C, RD_NOT_AUTHORIZED)
#define I2C_FATAL_FAIL                   MAKERESULT(RL_FATAL, RS_INTERNAL    , RM_I2C, RD_NO_DATA)
#define I2C_NOT_IMPLEMENTED              MAKERESULT(RL_USAGE, RS_NOTSUPPORTED, RM_I2C, RD_NOT_IMPLEMENTED)


#endif
